version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsbase
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-service-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmbase
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.19.0.2:5432/statsbase
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.19.0.2:5432/ewmbase
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root

  #-----------------------------------------------

#version: '3.1'
#services:
#
#  statistics-db:
#    image: postgres:14-alpine
#    container_name: statistics_postgres_container
#    ports:
#      - "6541:5431"
#    environment:
#      - POSTGRES_DB=statistics-db
#      - POSTGRES_USER=iamstatsroot
#      - POSTGRES_PASSWORD=iamstatsroot

  #  event-db:
  #    image: postgres:14-alpine
  #    container_name: events_postgres_container
  #    ports:
  #      - "6542:5432"
  #    environment:
  #      - POSTGRES_DB=event-db
  #      - POSTGRES_USER=iameventroot
  #      - POSTGRES_PASSWORD=iameventroot

#  statistics-server:
#    build: statistics-service/statistics-server
#    image: statistics_server_image
#    container_name: statistics_server_container
#    ports:
#      - "9090:9090"
#    depends_on:
#      - statistics-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5431/statistics-db
#      - SPRING_DATASOURCE_USERNAME=iamstatsroot
#      - SPRING_DATASOURCE_PASSWORD=iamstatsroot

#  event-service:
#    build: ./event-service
#    image: event_server_image
#    container_name: event_server_container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - event-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/event-db
#      - SPRING_DATASOURCE_USERNAME=iameventroot
#      - SPRING_DATASOURCE_PASSWORD=iameventroot
#      - STATS_SERVER_URL=http://localhost:9090

