version: '3.1'
services:
  stats:
    build: stats
    image: stats-image
    container_name: stats-container
    ports:
      - "9090:9090"
    depends_on:
      - main-service
      - stats-db
    environment:
      - STATS_SERVER_URL=http://server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/statsbase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-server-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmbase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  main-service:
    build: main-service
    image: main-service-image
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - main-service-db

  main-service-db:
    image: postgres:14-alpine
    container_name: main-service-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=mainbase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


#
#version: '3.8'
#services:
#  gateway:
#    build: gateway
#    image: shareit_gateway_image
#    container_name: gateway-container
#    ports:
#      - "8080:8080"
#    #      - "8081:8081"
#    depends_on:
#      - server
#      - db
#    environment:
#      - SHAREIT_SERVER_URL=http://server:9090
#  #      - ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
#
#  server:
#    build: server
#    image: shareit_server_image
#    container_name: server-container
#    ports:
#      - "9090:9090"
#    #      - "9091:9091"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=root
#  #      - ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9091
#
#  db:
#    image: postgres:14-alpine
#    volumes:
#      - /var/lib/postgresql/data/
#    container_name: shareIt-db
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_DB=shareit
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=root