version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsbase
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-service-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmbase
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsbase
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmbase
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root

